version: '3.1'

services:
  db:
    image: mysql:5.7
    env_file: ./env/.envmysql
    volumes:
      - db_collections:/var/lib/mysql
      - ./mysql-autoload:/docker-entrypoint-initdb.d:ro

  api:
    image: dina/collections-api:v0.1
    env_file:
      - ./env/.envaccounts
    environment:
      - VIRTUAL_HOST=alpha-api.dina-web.net
      - VIRTUAL_PORT=8080
    links:
      - db:mysql

# running with external proxy (check the network 'docker network ls')
networks:
  default:
    external:
      name: dwproxy_default

# docker volume ls
volumes:
  db_collections:
