version: '3'

services:

  # MySQL database for Keycloak
  db:
    image: mysql:latest
    env_file: ./env/.envmysql 
    volumes:
      - db_collections:/var/lib/mysql
      - ./mysql-autoload:/docker-entrypoint-initdb.d:ro

 
# Java JSON-API
  api:
    image: dina/collections-api:v0.1
    env_file:  
      - ./env/.envaccounts
    environment:
      - VIRTUAL_HOST=beta-api.dina-web.net
      - VIRTUAL_PORT=8080
#   volumes:
#     - ./env/.envapi:/usr/src/myapp/project-initdata.yml
#    ports:
#      - "8181:8181"
    links:
      - db:mysql

# Generic proxy
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

 
volumes:
  db_collections: 
